

export const coursesPlans: Array<IPlan> = [
  {
    header: "Stock Market Basics",
    type: ["Trading", "Investing"],
    off: "50% OFF",
    title: "Beginner's Guide to Stock Trading",
    courses: ["Introduction to Stock Market", "How Stock Exchanges Work", "Basic Trading Strategies"],
    workload: "12 weeks / 3 lessons per week, 1.5 h each",
    standardPlan: "₹ 30,000", 
    totalPrice: "₹ 15,000",   
    monthlyPrice: "₹ 1,250",  
  },
  {
    header: "Technical Analysis",
    type: ["Trading", "Analysis"],
    off: "30% OFF",
    title: "Mastering Technical Analysis",
    courses: ["Chart Patterns", "Indicators and Oscillators", "Trend Analysis"],
    workload: "8 weeks / 2 lessons per week, 2 h each",
    standardPlan: "₹ 40,000", 
    totalPrice: "₹ 28,000",    
    monthlyPrice: "₹ 2,333",    
  },
  {
    header: "Options Trading",
    type: ["Options", "Investing"],
    off: "40% OFF",
    title: "Advanced Options Trading Strategies",
    courses: ["Options Basics", "Call and Put Options", "Risk Management in Options"],
    workload: "10 weeks / 3 lessons per week, 2 h each",
    standardPlan: "₹ 50,000",   
    totalPrice: "₹ 30,000",     
    monthlyPrice: "₹ 2,500",      
  },
  {
    header: "Cryptocurrency Trading",
    type: ["Cryptocurrency", "Trading"],
    off: "25% OFF",
    title: "Cryptocurrency Trading for Beginners",
    courses: ["Introduction to Cryptocurrencies", "Trading Platforms", "Crypto Portfolio Management"],
    workload: "6 weeks / 2 lessons per week, 1.5 h each",
    standardPlan: "₹ 20,000",   
    totalPrice: "₹ 15,000",    
    monthlyPrice: "₹ 1,250",    
  },
  {
    header: "Algorithmic Trading",
    type: ["Programming", "Trading"],
    off: "20% OFF",
    title: "Automating Stock Trading with Algorithms",
    courses: ["Python for Trading", "Backtesting Strategies", "Building Trading Algorithms"],
    workload: "16 weeks / 3 lessons per week, 2 h each",
    standardPlan: "₹ 75,000",   
    totalPrice: "₹ 60,000",      
    monthlyPrice: "₹ 5,000",      
  },
  {
    header: "Fundamental Analysis",
    type: ["Investing", "Analysis"],
    off: "35% OFF",
    title: "Mastering Fundamental Analysis",
    courses: ["Analyzing Financial Statements", "Valuation Methods", "Company Analysis Techniques"],
    workload: "10 weeks / 3 lessons per week, 1.5 h each",
    standardPlan: "₹ 45,000", 
    totalPrice: "₹ 30,000",     
    monthlyPrice: "₹ 2,500",    
  },
  {
    header: "Forex Trading",
    type: ["Forex", "Trading"],
    off: "40% OFF",
    title: "Forex Trading Strategies",
    courses: ["Understanding Forex Markets", "Currency Pairs", "Technical and Fundamental Analysis for Forex"],
    workload: "8 weeks / 3 lessons per week, 1.5 h each",
    standardPlan: "₹ 35,000",   
    totalPrice: "₹ 21,000",     
    monthlyPrice: "₹ 1,750",   
  },
  {
    header: "Day Trading Strategies",
    type: ["Day Trading", "Investing"],
    off: "45% OFF",
    title: "Mastering Day Trading",
    courses: ["Scalping Strategies", "Momentum Trading", "Risk Management for Day Traders"],
    workload: "10 weeks / 4 lessons per week, 1.5 h each",
    standardPlan: "₹ 55,000",  
    totalPrice: "₹ 30,000",     
    monthlyPrice: "₹ 2,500",      
  },
  {
    header: "Risk Management",
    type: ["Trading", "Investing"],
    off: "30% OFF",
    title: "Risk Management in Stock Trading",
    courses: ["Identifying Market Risks", "Portfolio Diversification", "Hedging Strategies"],
    workload: "6 weeks / 2 lessons per week, 2 h each",
    standardPlan: "₹ 30,000",  
    totalPrice: "₹ 21,000",      
    monthlyPrice: "₹ 1,750",      
  },
  {
    header: "Behavioral Finance",
    type: ["Investing", "Psychology"],
    off: "25% OFF",
    title: "Understanding Behavioral Finance in Trading",
    courses: ["Investor Psychology", "Cognitive Biases in Trading", "Decision Making Under Uncertainty"],
    workload: "5 weeks / 3 lessons per week, 1.5 h each",
    standardPlan: "₹ 25,000",   
    totalPrice: "₹ 20,000",     
    monthlyPrice: "₹ 1,667",    
  },
  {
    header: "Portfolio Management",
    type: ["Investing", "Wealth Management"],
    off: "20% OFF",
    title: "Managing Investment Portfolios",
    courses: ["Building a Diversified Portfolio", "Asset Allocation", "Performance Evaluation"],
    workload: "8 weeks / 3 lessons per week, 2 h each",
    standardPlan: "₹ 50,000", 
    totalPrice: "₹ 40,000",      
    monthlyPrice: "₹ 3,333",    
  },
  {
    header: "ETF Trading",
    type: ["Investing", "ETFs"],
    off: "15% OFF",
    title: "Trading Exchange-Traded Funds (ETFs)",
    courses: ["Introduction to ETFs", "Trading Strategies", "Sector-Based ETFs"],
    workload: "6 weeks / 2 lessons per week, 1.5 h each",
    standardPlan: "₹ 30,000",   
    totalPrice: "₹ 25,000",    
    monthlyPrice: "₹ 2,083",     
  },
  {
    header: "Swing Trading",
    type: ["Trading", "Investing"],
    off: "25% OFF",
    title: "Mastering Swing Trading",
    courses: ["Introduction to Swing Trading", "Chart Patterns for Swing Traders", "Managing Trades"],
    workload: "7 weeks / 3 lessons per week, 1.5 h each",
    standardPlan: "₹ 40,000",  
    totalPrice: "₹ 30,000",
    monthlyPrice: "₹ 2,500",     
  },
];
